### PR TITLE
PTNFLY-1169 New PatternFly.org Pattern Page Update

### PR DESCRIPTION
**Pull request by dlabrecq**
Modified page title and tab to be on same line per new wireframes -- tab shown on own line for small screens.
Renamed tab from "reference implementation" to "HTML/CSS".
Removed max height style for prettyprint area in order to omit scrolling.
Added collapsable toggle around prettyprint -- shown expanded by default.
Added responsive CSS for large screens with design tab to address spacing issues between graphic and text.
Added index at the top of the page so user can jump to various sections.
Fixed anchors to use name instead of href

### CODE REVIEW

**Comment by rhamilto** [comment]
Hi, @dlabrecq.  Why are you adding a[name] elements?  Per the [HTML5 spec](https://www.w3.org/TR/html5/obsolete.html)

> Authors should not specify the name attribute on a elements. 

ID attributes on elements fulfill this need.

**Comment by dlabrecq** [comment]
My mistake -- ran into an issue testing. I'll correct it.

**Comment by dlabrecq** [comment]
Squashed commits. Merge please?

**Comment by dtaylor113** [comment]
LGTM

**Pull request merged**
