### PR TITLE
Bumped version number to 3.3.3

### PR DESCRIPTION
**Pull request by dlabrecq**
@dtaylor113 @jeff-phillips-18 please review

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Is there a reason all the angular-patternfly stuff is checked in? Can't it just be bower installed?

**Comment by dlabrecq** [comment]
All this is typically pushed to the OpenShift repo, so I assumed it's needed to run the site? I don't know if OpenShift will build this on its own?

**Comment by jeff-phillips-18** [comment]
But before it is pushed, could it be built (pulled via bower)?

**Comment by dlabrecq** [comment]
Not certain I understand what you're asking? I don't believe OpenShift is building anything for us because the entire source/components has been added to the repo.

I also see that library/components is also checked into patternfly-site. In both cases, the .gitignore file only ignores the node_modules directory.

**Comment by jeff-phillips-18** [comment]
The issue I have is that a simple change like the version number requires 110 file changes making any review very difficult. Do the files really need to be in git or could, prior to the push to OpenShift, bower install be run to pull the files? How are these files pushed? Is it all automated requiring a git pull to get these files somewhere?

**Comment by dtaylor113** [comment]
Think we need to update the PatternFly Release Process gDoc to include what steps we do to update pf.v2 site:
https://docs.google.com/document/d/1aHe0Yyl6jH6ZUFgsm-cUFy7R0wXm9KNZq2oeGjZEt9Q/edit#heading=h.e49hcela0aob

Dev Setup notes indicate that it requires Ruby (not sure why).  I don't think we have Ruby installed on the OpenShift instance:
https://github.com/patternfly/patternfly-toolkit/blob/master/README.md#development-setup

**Comment by dtaylor113** [comment]
Hi Dan,
Where are the instructions you are using to post pf.v2 changes to OpenShift?
Thanks,
- Dave

**Comment by dlabrecq** [comment]
> The issue I have is that a simple change like the version number requires 110 file changes making any review very difficult. Do the files really need to be in git or could, prior to the push to OpenShift, bower install be run to pull the files? How are these files pushed? Is it all automated requiring a git pull to get these files somewhere?

Can this build issue be address separately from this commit?

**Comment by jeff-phillips-18** [comment]
It's just really hard to approve this PR with so many file changes for a version number bump, but I guess.... LGTM

**Comment by dtaylor113** [comment]
LGTM, but we should add a JIRA story to capture documenting and optimizing pf.v2 builds.

**Comment by LHinson** [comment]
@dtaylor113 @dlabrecq happy to add a jira story but need to know what the verification conditions would be for this.

**Comment by dlabrecq** [comment]
@dtaylor113 - The pf.v2 update instructions from Robb were to commit changes directly to the OpenShit repo. There is no Jenkins build as with angular-patternfly.

@LHinson - I believe we need to discuss how we expect the build should work and if we want to make changes?

Questions:
Do we continue to commit the bower components directory?
Do we commit the bower components directory for OpenShift only?
Do we introduce a Jenkins build to create the components directory, instead?

**Comment by dtaylor113** [comment]
@dlabrecq "The pf.v2 update instructions from Robb..."  Did he send you a separate email, or are these instructions on a web page somewhere?
Thanks
- Dave

**Comment by dlabrecq** [comment]
It was word of mouth, during a meeting. We'll have to add instructions to the gDoc ourselves.

**Comment by dlabrecq** [comment]
> Dev Setup notes indicate that it requires Ruby (not sure why). I don't think we have Ruby installed on the OpenShift instance:

@dtaylor113 We don't use Ruby on OpenShift, but it's required for the Jekyll gem.

**Pull request merged**
